aws_region               = "eu-central-1"
bucket_prod              = "prod-mywebsite-bucket"
github_connection_name   = "my-github-connection"
github_repo              = "bortolo/my-website-for-codepipeline"
pipeline_name            = "my-github-pipeline"