---
- hosts: all
  remote_user: "{{user}}"

  vars:
    user: ec2-user
    cpu: 1
    seconds: 30
    region: eu-central-1
    conf_path_origin: ./awscli.conf
    conf_path_target: /etc/awslogs/awscli.conf

  tasks:

    - name: Install aws plugins to enable stress suite
      become: yes
      command: amazon-linux-extras install epel -y

    - name: Install awslogs and stress suite
      become: yes
      yum:
        update_cache: yes
        name:
        - awslogs
        - stress
        state: present

    - name: Copy config files for log groups
      become: yes
      copy:
       src: "{{conf_path_origin}}"
       dest: "{{conf_path_target}}"
    
    - name: Start  AWS log service
      become: yes
      systemd:
        state: started
        name: awslogsd
 
    - name: Run stress command on CPU
      command: stress --cpu {{cpu}} --timeout {{seconds}}
