aws_region                       = "eu-central-1"
application_name                 = "my-angular-app"
pipeline_name                    = "my-github-pipeline-ecs"
codebuild_name                   = "my-angular-build-ecs"
github_repo                      = "bortolo/my-angular-repo-docker"
github_connection_name           = "my-github-connection"
ecr_buildspec_name               = "buildspec-ECR.yml"