#!/bin/bash
yum update -y
yum install aws-kinesis-agent -y
wget http://media.sundog-soft.com/AWSBigData/LogGenerator.zip
unzip LogGenerator.zip
chmod a+x LogGenerator.py
mkdir /var/log/cadabra
service aws-kinesis-agent start
chkconfig aws-kinesis-agent on