aws_region               = "eu-central-1"
bucket_prod              = "prod-mywebsite-bucket"
github_connection_name   = "my-github-connection"
github_repo              = "bortolo/my-angular-repo"
pipeline_name            = "my-github-pipeline"
codebuild_name           = "my-angular-build"